server:
  port: 1919

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/pointdb1
    username: root
    password: x5
    driver-class-name: com.mysql.jdbc.Driver
# 配置Mybatis
mybatis:
  config-location: classpath:mybatis.xml

